[package]
name = "oliv-tokenizer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license = "MIT"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
tokenizers = { version = "0.22", default-features = false, features = ["onig"] }

[dev-dependencies]
serde_json = "1"
